### ISSUE TITLE
Review Requirements

### ISSUE THREAD

**Issue by irematik** [umkc-cs-451-2020-spring/semester-project-group-7#36]

**Comment by sahoahfoa** [comment]
What requirements do we have left to tick?

Also please verify the password requirements match the current implementation.

**Comment by sahoahfoa** [comment]
Upon checking the password requirements in the Software Requirement Specification doc I found that we currently don't have meet the requirement. We'll need to implement additional password validation with the following rules:
- At least 1 symbol (symbols is undefined. use best judgment)
- At least 1 Uppercase letter
- At least 1 number

**Comment by sahoahfoa** [comment]
After re-reading the requirements doc I noticed a few got missed:

1. Transactions should be exportable to a spreadsheet
2. Force sign-out after 10 minutes or inactivity and only allow one session per user
3. Hide all but the last 4 of the account number

Considering 2 should there even be a 'Remember Me' feature on the login page?
