### ISSUE TITLE
Update HTML templates and css

### ISSUE THREAD

**Issue by irematik** [umkc-cs-451-2020-spring/semester-project-group-7#44]

**Comment by sahoahfoa** [comment]
Lots of error messages and some the app language needs to be changed. 
There are a few places that have development verbiage that needs to be replaced as it is not user friendly. I see most of it in the trigger creating area. Expressing this in a user friendly way seem fairly difficult. 

The styles and layout for all pages should be done and looks good on mobile and desktop.

**Comment by sahoahfoa** [comment]
Finished updating templates
